import { format } from "date-fns";

interface ExpenseRow {
  id: string;
  merchant: string;
  category: string;
  amount: number;
  date: string;
  payment_method: string;
  note: string | null;
}

// ── CSV Export ──────────────────────────────────────────────
export function exportExpensesToCSV(expenses: ExpenseRow[], filename?: string) {
  const headers = ["Date", "Merchant", "Category", "Amount", "Payment Method", "Note"];
  const rows = expenses.map((e) => [
    e.date,
    `"${e.merchant.replace(/"/g, '""')}"`,
    e.category,
    e.amount.toFixed(2),
    e.payment_method,
    `"${(e.note || "").replace(/"/g, '""')}"`,
  ]);

  const csv = [headers.join(","), ...rows.map((r) => r.join(","))].join("\n");
  downloadBlob(csv, filename || `expenses-${format(new Date(), "yyyy-MM-dd")}.csv`, "text/csv");
}

// ── PDF Export (pure HTML → print) ─────────────────────────
export function exportExpensesToPDF(expenses: ExpenseRow[], title?: string) {
  const total = expenses.reduce((s, e) => s + e.amount, 0);
  const reportTitle = title || `Expense Report — ${format(new Date(), "MMMM yyyy")}`;

  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>${reportTitle}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', system-ui, -apple-system, sans-serif; color: #1a1a2e; padding: 40px; }
    .header { display: flex; justify-content: space-between; align-items: flex-end; margin-bottom: 32px; border-bottom: 3px solid #0d9488; padding-bottom: 16px; }
    .header h1 { font-size: 22px; font-weight: 700; color: #0d9488; }
    .header .meta { font-size: 12px; color: #666; text-align: right; }
    .summary { display: flex; gap: 24px; margin-bottom: 28px; }
    .summary-card { background: #f0fdfa; border: 1px solid #ccfbf1; border-radius: 8px; padding: 16px 20px; flex: 1; }
    .summary-card .label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: #666; }
    .summary-card .value { font-size: 24px; font-weight: 700; color: #0d9488; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th { text-align: left; padding: 10px 12px; background: #f8fafc; border-bottom: 2px solid #e2e8f0; font-weight: 600; font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: #475569; }
    td { padding: 10px 12px; border-bottom: 1px solid #f1f5f9; }
    tr:hover { background: #f8fafc; }
    .amount { font-weight: 600; color: #dc2626; text-align: right; }
    .category { display: inline-block; padding: 2px 8px; border-radius: 4px; background: #f0fdfa; color: #0d9488; font-size: 11px; font-weight: 500; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>💰 ${reportTitle}</h1>
    <div class="meta">
      Generated: ${format(new Date(), "MMM d, yyyy 'at' h:mm a")}<br/>
      FinAI — AI-Powered Finance Manager
    </div>
  </div>
  <div class="summary">
    <div class="summary-card">
      <div class="label">Total Expenses</div>
      <div class="value">$${total.toFixed(2)}</div>
    </div>
    <div class="summary-card">
      <div class="label">Transactions</div>
      <div class="value">${expenses.length}</div>
    </div>
    <div class="summary-card">
      <div class="label">Avg per Transaction</div>
      <div class="value">$${expenses.length > 0 ? (total / expenses.length).toFixed(2) : "0.00"}</div>
    </div>
  </div>
  <table>
    <thead>
      <tr><th>Date</th><th>Merchant</th><th>Category</th><th>Payment</th><th>Note</th><th style="text-align:right">Amount</th></tr>
    </thead>
    <tbody>
      ${expenses
        .map(
          (e) => `<tr>
        <td>${e.date}</td>
        <td>${e.merchant}</td>
        <td><span class="category">${e.category}</span></td>
        <td>${e.payment_method}</td>
        <td>${e.note || "—"}</td>
        <td class="amount">-$${e.amount.toFixed(2)}</td>
      </tr>`
        )
        .join("")}
    </tbody>
  </table>
  <div class="footer">This report was generated by FinAI. All data is confidential.</div>
  <script>window.onload = () => { window.print(); }</script>
</body>
</html>`;

  const w = window.open("", "_blank");
  if (w) {
    w.document.write(html);
    w.document.close();
  }
}

// ── Dashboard Summary PDF ──────────────────────────────────
interface DashboardSummary {
  totalSaved: number;
  totalExpenses: number;
  goalCount: number;
  goalPct: number;
  spendingByCategory: { category: string; amount: number }[];
  topGoals: { name: string; saved: number; target: number }[];
}

export function exportDashboardPDF(summary: DashboardSummary) {
  const html = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>Financial Summary</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Segoe UI', system-ui, sans-serif; color: #1a1a2e; padding: 40px; }
    .header { border-bottom: 3px solid #0d9488; padding-bottom: 16px; margin-bottom: 32px; }
    .header h1 { font-size: 22px; font-weight: 700; color: #0d9488; }
    .header p { font-size: 12px; color: #666; margin-top: 4px; }
    .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 16px; margin-bottom: 32px; }
    .stat { background: #f0fdfa; border: 1px solid #ccfbf1; border-radius: 8px; padding: 16px; }
    .stat .label { font-size: 11px; text-transform: uppercase; letter-spacing: 0.5px; color: #666; }
    .stat .value { font-size: 22px; font-weight: 700; color: #0d9488; margin-top: 4px; }
    h2 { font-size: 16px; font-weight: 600; margin: 24px 0 12px; color: #1a1a2e; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; margin-bottom: 24px; }
    th { text-align: left; padding: 8px 12px; background: #f8fafc; border-bottom: 2px solid #e2e8f0; font-size: 11px; text-transform: uppercase; color: #475569; }
    td { padding: 8px 12px; border-bottom: 1px solid #f1f5f9; }
    .bar-bg { background: #e2e8f0; border-radius: 4px; height: 8px; width: 100%; }
    .bar-fill { background: #0d9488; border-radius: 4px; height: 8px; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; font-size: 11px; color: #94a3b8; text-align: center; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <div class="header">
    <h1>💰 Financial Summary Report</h1>
    <p>Generated on ${format(new Date(), "MMMM d, yyyy")} · FinAI</p>
  </div>
  <div class="grid">
    <div class="stat"><div class="label">Total Saved</div><div class="value">$${summary.totalSaved.toLocaleString()}</div></div>
    <div class="stat"><div class="label">Total Expenses</div><div class="value">$${summary.totalExpenses.toLocaleString()}</div></div>
    <div class="stat"><div class="label">Active Goals</div><div class="value">${summary.goalCount}</div></div>
    <div class="stat"><div class="label">Goal Progress</div><div class="value">${summary.goalPct}%</div></div>
  </div>
  ${summary.spendingByCategory.length > 0 ? `
  <h2>Spending by Category</h2>
  <table>
    <thead><tr><th>Category</th><th style="text-align:right">Amount</th></tr></thead>
    <tbody>${summary.spendingByCategory.map(c => `<tr><td>${c.category}</td><td style="text-align:right;font-weight:600">$${c.amount.toLocaleString()}</td></tr>`).join("")}</tbody>
  </table>` : ""}
  ${summary.topGoals.length > 0 ? `
  <h2>Goals Progress</h2>
  <table>
    <thead><tr><th>Goal</th><th>Saved</th><th>Target</th><th>Progress</th></tr></thead>
    <tbody>${summary.topGoals.map(g => {
      const pct = g.target > 0 ? Math.round((g.saved / g.target) * 100) : 0;
      return `<tr><td>${g.name}</td><td>$${g.saved.toLocaleString()}</td><td>$${g.target.toLocaleString()}</td><td><div class="bar-bg"><div class="bar-fill" style="width:${pct}%"></div></div> ${pct}%</td></tr>`;
    }).join("")}</tbody>
  </table>` : ""}
  <div class="footer">This report was generated by FinAI. All data is confidential.</div>
  <script>window.onload = () => { window.print(); }</script>
</body>
</html>`;

  const w = window.open("", "_blank");
  if (w) {
    w.document.write(html);
    w.document.close();
  }
}

// ── Helper ─────────────────────────────────────────────────
function downloadBlob(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
